config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'friends/new', to:'friends#new'
  get '/about', to:'home#about'
  # get '/friends', to:'friends#index'
  # get '/show', to:'friends#show'
  # get 'home/index'
  resources :friends
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
    before_save {self.email = email.downcase}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :first_name, presence: true, length: { maximum:50 }
    validates :last_name, presence: true, length: {maximum: 50}
    validates :email, presence: true, length: {maximum: 255}, format: { with: VALID_EMAIL_REGEX }, uniqueness: true
    validates :phone, presence: true, length: {maximum: 30}
    validates :twitter, presence: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController

  # get friends
  def index
    @friends= Friend.all
  end

  # get friends/1
  def show
    @friend = Friend.find(params[:id])
  end

  # get friends/new
  def new
   @friend = Friend.new
  end

  # get /friends/1/edit
  def edit
    @friend = Friend.find(params[:id])
  end

  # post friends
  def create
    @friend= Friend.new(user_params)
    if @friend.save
      flash[:success]= "You successfully registered #{@friend.first_name}" 
      redirect_to @friend
    else
      # flash[:danger]= " unsuccessfully registeration" 
      render 'new'
    end

  end

  def update
    @friend = Friend.find(params[:id])
    if @friend.update(user_params)
      flash[:success]="Your profile updated successfully"
      redirect_to friends_url
    else
      flash[:danger]="Your not updated successfully"
      render 'edit'
    end

  end
  
  def destroy
    @friend = Friend.find(params[:id])
    if @friend.destroy
      flash[:success]="Friend Deleted successfuly"
      redirect_to @friend
    else
      flash[:danger]="Friend not deleted successfully"
    end

  end

  private
  def user_params
    params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter)
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
    def gravatar_for(friend, size: 80)
        gravatar_id = Digest::MD5::hexdigest(friend.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#
        {gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: friend.first_name, class: "gravatar")
    end
            
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/edit.html.erb
<% provide(:button_text, 'Update Friend')%>
<div class="container">
    <div class="card text-center" style="margin-top: 50px;margin-left:100px; margin-right:100px;">
        <div class="card-header">
            Update your profile 
        </div>
        <div class="card-body">
            <!-- <div class="gravatar_edit">
                <%= gravatar_for @friend %>
                <a href="https://gravatar.com/emails"
                target="_blank">Change</a>
                </div> -->
                <br>
            <%= render 'layouts/form' , friend: @friend %>     
        </div>
        <div class="card-footer text-muted" style="padding-left:500px;">
            <%= link_to 'Home', root_path %>
            <%= link_to 'About' , about_path %>
            <%= link_to 'Back' , friends_path %>
        </div>

    </div>
</div>

app/views/friends/index.html.erb
 <div class="container">
 <h1 style="margin-top: 40px;"> List Of Friends</h1>
 <br>

<ul>
    <table class="table">
        <thead class="table">
            <th> Name </th>
            <th> Email </th>
            <th> Phone </th>
            <th> Twitter </th>
            <th> Actions </th>
            <th> </th>
        </thead>
        <% @friends.each do |friend| %>
        <tbody>
            <tr>
                <td> <li><%= link_to friend.first_name + ' ' +friend.last_name, friend_path(friend) %> </td>
                <td> <%= friend.email %> </td>
                <td> <%= friend.phone %> </td>
                <td> <%= friend.twitter %> </td>
                <td> <button><%= link_to 'Edit', edit_friend_path(friend) %></button> </td>
                <td> <button><%= link_to 'Delete', friend, method: :delete, data:{ confirm:'Are you sure?' } %></button> </td>
            </tr>
        </tbody>
        <%end%>
    </table>
    
    
    
</ul>

<%= link_to 'Back', friends_new_path %>

</div>

app/views/friends/new.html.erb
<% provide(:button_text, 'Create Friend')%>
<div class="card text-center" style="margin-top: 50px;margin-left:100px; margin-right:100px;">
    <div class="card-header">
        Add New Friends <%= link_to 'List Friends' , friends_path, class:'btn btn-secondary'%>
    </div>
    <div class="card-body">
        <%= render 'layouts/form', friend: @friend %>
    </div>
    <div class="card-footer text-muted" style="padding-left:500px;">
        <%= link_to 'Home' , root_path %>
            <%= link_to 'About' , about_path %>
            <%= link_to 'Back', root_path %>
    </div>

</div>

app/views/friends/show.html.erb
<div class="container" style="margin-top:30px">
    <div class="row">
        <aside class="col-md-4">
            <section class="user_info">
                <h1>
                    <%= gravatar_for @friend%>
                    <strong>Email:</strong>
                    <%= @friend.email %>
                </h1>
            </section>
        </aside>
    </div>
    <%= link_to 'Back', friends_path %>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to 'Friend Kit', root_path, class:"navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
  
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
         <%= link_to 'About Us' , about_path , class:"nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to 'Friends' , friends_new_path , class:"nav-link"%>
     </li>
    </ul>
</div>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>

</nav>

app/views/home/about.html.erb
<div class="container">
    <h1> ABOUT US ...</h1>
</div>

app/views/home/index.html.erb
<div class="container">
    <h1>HELLO WORLD!</h1>
</div>

app/views/layouts/_form.html.erb
<%= form_with( model: friend, local: true ) do |form| %>
    <% render 'shared/error_messages'%>
    <div class="form-row">
        <div class="form-group col-md-6">
            <div class="field">
                <%= form.label :first_name %>
                <%= form.text_field :first_name, class: 'form-control'  %>
            </div>
        </div>
        <div class="form-group col-md-6">
            <div class="field">
                <%= form.label :last_name %>
                <%= form.text_field :last_name, class: 'form-control'  %>
            </div>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <div class="field">
                <%= form.label :email %>
                <%= form.text_field :email, class: 'form-control'  %>
            </div>
        </div>
        <div class="form-group col-md-6">
            <div class="field">
                <%= form.label :phone %>
                <%= form.text_field :phone, class: 'form-control'  %>
            </div>
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col-md-6">
            <div class="field">
                <%= form.label :twitter %>
                <%= form.text_field :twitter, class: 'form-control'  %>
            </div>
        </div>
        <div class="form-group col-md-6">
        </div>
    </div>
    <div>
        <%= form.submit yield(:button_text), class: "btn btn-secondary" %>
    </div>
    <% end %>
        <!-- 
<form>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="first_name">First Name</label>
            <input type="text" class="form-control" placeholder="First name" id="first_name">
        </div>
        <div class="form-group col-md-6">
            <label for="last_name">Last Name</label>
            <input type="text" class="form-control" placeholder="First Name" id="last_name">
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="inputEmail4">Email</label>
            <input type="email" class="form-control" id="inputEmail4"  placeholder="Email">
        </div>
        <div class="form-group col-md-6">
            <label for="phone">Phone Number</label>
            <input type="text" class="form-control" placeholder="Phone" id="phone">
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="twitter">Twitter</label>
            <input type="text" class="form-control" id="twitter" placeholder="Twitter">
        </div>
        <div class="form-group col-md-6">
        </div>
    </div>


    <button type="submit" class="btn btn-secondary">Add Friend</button>
</form> -->

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script
src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.j
s">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Friendskit</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim'%>
  </head>

  <body>
    <%= render 'home/header' %>
    <div class="container" style="margin-top: 20px;">
      <% flash.each do |message_type, message| %>
       <div class="alert alert-<%= message_type %>"><%= message %></div>
       <% end %>
    </div>
    <%= yield %>
    <!-- <%= debug(params) if Rails.env.development? %> -->
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @friend.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-danger">
            The form contains <%= pluralize(@friend.errors.count, "error" ) %>.
        </div>
        <ul>
            <% @friend.errors.full_messages.each do |msg| %>
                <li>
                    <%= msg %>
                </li>
                <% end %>
        </ul>
    </div>
    <% end %>